apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myfirstapp:v3
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: "/storage/"
            name: task-pv-storage
          - name: secret-mount
            mountPath: "/tmp/"
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: mypvc
        - name: secret-mount
          secret:
            secretName: certs
---
kind: Service
apiVersion: v1
metadata:
  name: mysvc
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 32321
  type: NodePort


