apiVersion: v1
kind: Service
metadata:
  name: {{ include "myfirstapp.fullname" . }}
  labels:
    {{- include "myfirstapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 32321
      protocol: TCP
  selector:
    {{- include "myfirstapp.selectorLabels" . | nindent 4 }}